### ISSUE TITLE
conf is of 'NoneType'

### ISSUE THREAD

**Issue by alephpi** [sweetcocoa/ddsp-pytorch#5]
Hi, thanks for your work!
However, when trying to run train.py, I encounter the following error. The `conf` object created by `omegaconf` is of `NoneType`.

```Traceback (most recent call last):
  File "E:\WORKS\CS\ddsp-pytorch\train\train.py", line 26, in <module>   
    config = setup(default_config="../configs/violin.yaml")
  File "E:\WORKS\CS\ddsp-pytorch\train\trainer\io.py", line 119, in setup
    conf.save(logpath[:-4] + ".yaml")
TypeError: 'NoneType' object is not callable
```

Nothing changed from your scripts. And I skip step 1-5 since I just want to check the default experiment on violin. Could you give any insights on it?

I'm using `omegaconf==2.0.6`

**Comment by alephpi** [comment]
Well, indeed due to the imcompatibility of version, `omegaconf==1.4.0` works well. Refer to https://github.com/omry/omegaconf/issues/66
